- addon/components/materialize-date-input.js
- addon/components/materialize-input-field.js
- addon/components/materialize-select.js
- addon/components/materialize-textarea.js
- addon/templates/components/materialize-date-input.hbs
- addon/templates/components/materialize-input.hbs
- addon/templates/components/materialize-select.hbs
- addon/templates/components/materialize-textarea.hbs
- app/components/materialize-date-input.js
- app/components/materialize-input-field.js
- app/components/materialize-select.js
- app/components/materialize-textarea.js
- tests/dummy/app/controllers/input.js
- tests/dummy/app/templates/index.hbs
- tests/dummy/app/templates/input.hbs
- tests/unit/components/materialize-date-input-test.js
- tests/unit/components/materialize-input-field-test.js
- tests/unit/components/materialize-select-test.js
- tests/unit/components/materialize-textarea-test.js
@sgasser Here is a PR for adding form input components for TextArea, Date, and Select.
> create input components for Date, Select, and TextArea

- bower.json
- package.json
- tests/unit/components/materialize-button-test.js
Update to 
* Ember 1.11
* Ember-cli 0.2.1
* Ember-data 1.0.0-beta.16.1
> Update dev dependencies

- .editorconfig
- .npmignore
- .travis.yml
- LICENSE.md
- README.md
- bower.json
- package.json
Also...
* Add code climate
* Update license for 2015
* Add iojs 1.63 to travis-ci
> Update to ember-cli 0.2.2

- README.md
> Add emberobserver.com badge to Readme

- tests/unit/components/materialize-badge-test.js
- tests/unit/components/materialize-button-submit-test.js
- tests/unit/components/materialize-button-test.js
- tests/unit/components/materialize-card-action-test.js
- tests/unit/components/materialize-card-content-test.js
- tests/unit/components/materialize-card-panel-test.js
- tests/unit/components/materialize-card-reveal-test.js
- tests/unit/components/materialize-card-test.js
- tests/unit/components/materialize-collapsible-card-test.js
- tests/unit/components/materialize-collapsible-test.js
- tests/unit/components/materialize-date-input-test.js
- tests/unit/components/materialize-input-field-test.js
- tests/unit/components/materialize-input-test.js
- tests/unit/components/materialize-loader-test.js
- tests/unit/components/materialize-navbar-test.js
- tests/unit/components/materialize-parallax-test.js
- tests/unit/components/materialize-select-test.js
- tests/unit/components/materialize-textarea-test.js
This pull request will raise the code climate score from `1.94` to `2.9`
> Code climate improvements

- tests/integration/cards-test.js
This raises the code climate score from `2.9` to `3.15`
> Refactor cards-test

- .travis.yml
- config/ember-try.js
- travis-ci-ember-try.sh
> Run ember-try on travis-ci parallel

- addon/components/materialize-button.js
- addon/components/materialize-collapsible-card.js
- addon/components/materialize-date-input.js
- addon/components/materialize-input-field.js
- addon/components/materialize-input.js
- addon/components/materialize-loader.js
- addon/components/materialize-navbar.js
- addon/components/materialize-parallax.js
- addon/components/materialize-select.js
- addon/components/materialize-tabs-tab.js
- addon/components/materialize-tabs.js
- addon/components/materialize-textarea.js
- tests/integration/cards-test.js
- tests/integration/collapsible-test.js
- tests/integration/tabs-test.js
> ES6ification

- README.md
Hey there
Just started playing with the addon and thought it might be worth documenting how to configure the sass variables. Its not a big deal but might save some a few minutes and digging around in the bower module.
> added configuration block in README

- addon/templates/components/md-select.hbs
Bugfix for classname bindings in md-select.
Messed up my previous pull request, my apologies.
> Fixed classnamebinding in md-select

- addon/components/md-input-date.js
- package.json
- tests/dummy/app/controllers/forms.js
- tests/dummy/app/templates/forms.hbs
Apparently our date input didn't really work, in that it never connected anything to the appropriate pickadate.js event, to observe changes in value.
> [Bugfix] Datepicker input now updates bound value

- tests/dummy/app/templates/navbar.hbs
- tests/dummy/app/templates/pagination.hbs
> Fix deprecation in navbar docs

- addon/components/md-loader.js
Thanks @pajter -- I fixed the breaking tests for you since #98 was sitting around for a while
> Fixed possible XSS bug in md-loader style binding

- blueprints/ember-cli-materialize/index.js
> Update ember-modal-dialog to 0.7.0

- addon/components/selectable-item-group.js
- tests/helpers/selectable-item-group.js
- tests/unit/components/materialize-checkboxes-test.js
- tests/unit/components/materialize-radios-test.js
- tests/unit/components/materialize-switches-test.js
Cannot deselect checks if multiple=false.
https://github.com/sgasser/ember-cli-materialize/issues/133
> Fix issue #133

- addon/components/md-btn.js
- package.json
- tests/dummy/app/templates/buttons.hbs
> Pass argument along with action, when md-btn fires 

- addon/components/md-modal.js
- addon/templates/components/md-modal.hbs
- app/styles/ember-cli-materialize.scss
- blueprints/ember-cli-materialize/files/app/styles/app.scss
- blueprints/ember-cli-materialize/index.js
- package.json
- tests/dummy/app/styles/app.scss
- tests/integration/modal-test.js
> Modal fixes, blueprint update

- bower.json
- tests/dummy/app/controllers/application.js
- tests/dummy/app/controllers/colors.js
- tests/dummy/app/router.js
- tests/dummy/app/styles/app.scss
- tests/dummy/app/templates/colors.hbs
- tests/dummy/app/templates/forms.hbs
adding color guide #rainbows to documentation
> colors-page

- tests/dummy/app/templates/snippets/input-types.hbs
http://ionicframework.com/html5-input-types/#tel
> input type should be tel

- addon/components/md-navbar.js
- addon/templates/components/md-navbar.hbs
- tests/dummy/app/templates/navbar.hbs
- tests/dummy/app/templates/snippets/navbar-custom-home.hbs
- tests/integration/navbar-test.js
If you rename the home route from index to something else (such as namespacing it all under a `dashboard` route) then all hell breaks loose! Let's fix that.
> Make dat homeRoute customizable!!!

- bower.json
- config/ember-try.js
- package.json
Also this pulls in some bug fixes in ember-key-responder
> Add ember-legacy-views

- addon/components/md-modal.js
> [Canary] Replaced '@each' computed property with '[]' (fixes #202)

- addon/templates/components/md-collection.hbs
- package.json
> Yield index in collection block syntax

- blueprints/ember-cli-materialize/index.js
This adds the legacy view package to remove view deprecation warnings on the march to 1.0
> Added legacy views to added NPM packages to get rid of view warnings

- tests/dummy/app/templates/snippets/form-validation-basic.hbs
- tests/dummy/app/templates/snippets/input-basic.hbs
- tests/dummy/app/templates/snippets/input-date-basic.hbs
- tests/dummy/app/templates/snippets/input-types.hbs
- tests/dummy/app/templates/snippets/input-with-icon.hbs
- tests/dummy/app/templates/snippets/select-basic.hbs
- tests/dummy/app/templates/snippets/textarea-basic.hbs
Updates input related snippets to demonstrate the materializecss requirement of row/col markup for correct label alignment.
> #229 - Update input-related snippets to demonstrate correct label alignment

- README.md
As discussed in https://github.com/mike-north/ember-cli-materialize/issues/223, added note to readme, if you want it moved somewhere else in the readme order let me know.
> Add note to readme for phantomjs users #223

- blueprints/ember-cli-materialize/index.js
- package.json
This is based off of @kapolos's work with a slightly cleaner commit history...It does not seem to introduce any regressions...
> upgrade ember-cli-sass to be more modern

- package.json
> chore(package): update ember-composability to version 0.3.2

- addon/components/md-card-content.js
- addon/components/md-card-panel.js
- addon/components/md-card-reveal.js
- addon/components/md-card.js
- config/ember-try.js
- package.json
- tests/.jshintrc
- tests/helpers/module-for-acceptance.js
This might be the first addon to have image-based diff testing!
CC: @fotinakis
> Fix ember 2.7.0 deprecations, add Percy.io

- package.json
It is already in dependencies.
> Remove ember-cli-sass from devDependencies

- addon/components/md-btn.js
- addon/components/md-loader.js
- addon/components/md-modal-container.js
- addon/components/md-table-col.js
See http://emberjs.com/deprecations/v2.x/#toc_ember-binding
> Fix deprecation: Changed oneWay bindings to readOnly

- addon/components/md-btn.js
- tests/unit/components/materialize-button-test.js
> Do not fire click action from md-btn if isDisabled=true

- testem.js
This should fix (or at least help fix) currently broken CI builds.
> Pass --no-sandbox to Chrome in CI

- blueprints/ember-cli-materialize/index.js
- package-lock.json
- package.json
See https://github.com/mike-north/ember-cli-materialize/pull/641#issuecomment-360513251
> Update ember-keyboard to v3.0.0 (latest)

- addon/templates/components/md-collapsible.hbs
- tests/unit/components/materialize-collapsible-test.js
> Use bw-compat-icon in md-collapsible

- package.json
> chore(package): update ember-source to version 3.0.0-beta.4

- addon/components/md-select.js
> Improve setup & tear-down of md-select (didInsertElement -> didRender)

- tests/unit/components/md-fixed-btn-test.js
> test(md-fixed-btn) Add md-fixed-btn using icon test
