- README.md
- addon/initializers/link-view.js
- app/initializers/link-view.js
- tests/dummy/app/app.js
- tests/unit/initializers/link-view-test.js
Spent some time figuring out why my navbar wasn't working. "data-activates" attribute must be bound in LinkView.
The test isn't running in PhantomJS, but it is passing in Chrome. :/
Followed this method: http://pixelhandler.com/posts/develop-embercomponents-for-sharing-as-ember-cli-addons-a-practical-example#whataboutinitializers
> Reopen LinkView in an initializer

- blueprints/ember-cli-materialize/files/config/environment.js
The environment.js blueprint contained an extra semi-colon following the sassOptions block.
> Removed extra semi-colon

- addon/components/materialize-input.js
- addon/templates/components/materialize-input.hbs
- app/components/materialize-input.js
- tests/dummy/app/controllers/input.js
- tests/dummy/app/router.js
- tests/dummy/app/routes/input.js
- tests/dummy/app/templates/application.hbs
- tests/dummy/app/templates/index.hbs
- tests/dummy/app/templates/input.hbs
- tests/unit/components/materialize-input-test.js
This PR includes an input component that supports ember-validation style validation messages (error object on the model/controller) as well as html5 browser validation.  The component addresses an issue where the label does not move out of the input element when bound to a value as mentioned in an issue on the materializecss repo.  Icon prefix is also supported.
As the textarea component I have in mind has some similarities, I'll likely wait to see if this is merged to combine the commonalities.  Until i know whether this will be merged or not, I'll create a branch to work on the date input component so a separate PR can be created from there.
> Create component for form input

- tests/dummy/app/index.html
Currently the dummy app is looking for an `assets/ember-cli-materialize.css` file, which doesn't exist. I have changed the dummy app's index.html to look for `dummy.css`, which results in everything being rendered with the materialize css as expected.
> Fix dummy app CSS path

- addon/components/materialize-input.js
- addon/templates/components/materialize-input.hbs
- tests/dummy/app/templates/input.hbs
- tests/unit/components/materialize-input-test.js
`{{materialize-input value="test" label="Password" type="password"}}`
> Type of input can be set through parameter

- .travis.yml
- addon/templates/components/materialize-loader.hbs
- bower.json
- config/ember-try.js
- package.json
This pull request
* Removes all uses of attribute binding, which was breaking compatibility with ember 1.10
* Introduces the ember-try addon, to run tests against multiple versions of ember
* Configures ember-try to test this addon against `1.10.0`, `1.11.0`, `release` (currently 1.11.1) and `beta` (currently 1.12.beta-1)
* Lowers the required version of ember for this addon to 1.10 (was previously 1.11)
* Configures travis-ci to run `ember try:testall` in CI, so that only changes that pass all supported versions of ember are shown as passing pull requests. This means we'll be alerted to any further 1.10 incompatibilities
> Restore ember-1.10 compatibility, and add ember-try

- blueprints/ember-cli-materialize/files/config/environment.js
Fixes #50 
Looks like part of the app blueprint was copied over from ember-cli to start this addon's ember-cli-materialize blueprint, but we don't have access to the modulePrefix local variable, since our blueprint's index.js doesn't override the `locals` hook with anything special.
https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/index.js#L16
> Fix blueprint

- package.json
This fixes a dependency error described here
https://github.com/aexmachina/ember-cli-sass/issues/45
> Upgrade ember-cli-sass to 4.0.0-beta.4

- .travis.yml
PhantomJS 2.0.0 is less error prone, and more performant than 1.9.8
> Update travis.yml to use PhantomJS 2.0

- addon/components/materialize-button.js
- addon/components/materialize-collapsible-card.js
- addon/components/materialize-date-input.js
- addon/components/materialize-input-field.js
- addon/components/materialize-input.js
- addon/components/materialize-loader.js
- addon/components/materialize-navbar.js
- addon/components/materialize-parallax.js
- addon/components/materialize-select.js
- addon/components/materialize-tabs-tab.js
- addon/components/materialize-tabs.js
- addon/components/materialize-textarea.js
- tests/integration/cards-test.js
- tests/integration/collapsible-test.js
- tests/integration/tabs-test.js
I gave the entire addon a quick pass and converted it to the new ES6 function syntax. Additionally, I cleaned up some needlessly verbose code, and consolidated some tests to avoid paying the cost of loading the app and visiting a route multiple times when not necessary.
> ES6ification

- tests/dummy/app/styles/app.scss
- tests/index.html
We should be using our CSS in our test runner, to validate that things look correct in acceptance tests.
Unfortunately, materialize screws up the test runner by styling naked tags and inputs
The most annoying part is that the module selector disappears completely. I have added some styles to our dummy app to fix this
We should consider shipping this CSS with ember-cli-materialize, so that our addon consumers don't suffer from the same problems in their own qunit test runners.
> Re-enable stylesheet in qunit test runner

- addon/components/materialize-pagination.js
- addon/templates/components/materialize-pagination.hbs
- app/components/materialize-pagination.js
- tests/dummy/app/controllers/pagination.js
- tests/dummy/app/router.js
- tests/dummy/app/templates/index.hbs
- tests/dummy/app/templates/pagination.hbs
- tests/unit/components/materialize-pagination-test.js
A pagination component that automatically calculates a range of pages to jump to, based on a min, a max, and a "width" of the window of page numbers. As the boundaries of the allowed range are approached, the "back" and "forward" buttons grey out and disable.
On the demo page, I provide an example of how to use a query param on a `Ember.Controller` in conjunction with this component, since it's likely to be the most common use case.
```handlebars
{{materialize-pagination min=1 max=12 current=page range=7}}
```
> Pagination

- addon/components/md-btn-submit.js
- addon/components/md-btn.js
- addon/components/md-card-collapsible.js
- addon/components/md-card-content.js
- addon/components/md-card-panel.js
- addon/components/md-card-reveal.js
- addon/components/md-card.js
- addon/components/md-check.js
- addon/components/md-collapsible.js
- addon/components/md-copyright.js
- addon/components/md-input-date.js
- addon/components/md-input-field.js
- addon/components/md-input.js
- addon/components/md-loader.js
- addon/components/md-modal.js
- addon/components/md-navbar.js
- addon/components/md-pagination.js
- addon/components/md-parallax.js
- addon/components/md-radio.js
- addon/components/md-range.js
- addon/components/md-select.js
- addon/components/md-switch.js
- addon/components/md-tab.js
- addon/components/md-tabs.js
- addon/components/md-textarea.js
- addon/components/selectable-item-group.js
- addon/components/selectable-item.js
- addon/mixins/group-selectable-item.js
- tests/integration/collapsible-test.js
* Switched us over to the new computed property syntax introduced in ember 1.12 - https://github.com/stefanpenner/rfcs/blob/ae07e7b1ce1996686c91250ebb2158a4eff4bce0/0000-improved-cp-syntax.md
* Found a few places where `this._super(...arguments)` was not called in `willDestroyElement`, `didInsertElement`, or `init` hook
* TODO'd some places where we're likely setting up listeners via materialize JavaScript on `didInsertElement`, and not properly tearing them down in `willDestroyElement`
* More ES6ification: converted string concatination to template strings, callbacks to arrow functions, etc...
> New CP syntax, cleanup, formatting

- package.json
Materialize already gives us velocity.js, which is used in our tabs component. Liquid-fire is awesome, and the best ember-idiomatic option for material-design-ish animations and transitions, but we don't need it for now.
> [Refactor] Remove liquid fire

- addon/components/md-select.js
- package.json
- tests/unit/components/materialize-checkboxes-test.js
- tests/unit/components/materialize-radios-test.js
- tests/unit/components/materialize-select-test.js
- tests/unit/components/materialize-switches-test.js
Fixes #74 
This introduces test coverage for simple array use cases in select, switches, checks and radios.
Example: 
```js
export default Ember.Component.extend({
choices: ['Dexter Morgan', 'Deborah Morgan', 'Harry Morgan'],
selectedChoice: 'Deborah Morgan'
});
```
```handlebars
{{md-select
content=choices
value=selectedChoice}}
```
or
```handlebars
{{md-radios
content=choices
selection=selectedChoice}}
```
> [Bugfix] Select - simple array case

- blueprints/ember-cli-materialize/index.js
- package.json
Nested addons should be in `dependencies`, not `devDependencies`
Fixes #79
> [Bugfix] Handle nested addons properly

- addon/components/md-modal-container.js
- addon/templates/components/md-modal-container.hbs
- app/components/md-modal-container.js
- blueprints/ember-cli-materialize/files/app/templates/application.hbs
- tests/dummy/app/styles/app.scss
- tests/dummy/app/templates/application.hbs
- tests/dummy/app/templates/modal.hbs
- tests/unit/components/md-modal-container-test.js
Fixes #81 
This PR adds a new component
```handlebars
{{md-modal-container}}
```
Which the user should add to their `application.hbs`. Modals are rendered as DOM children of this component (but their view hierarchy can really be anything, thanks to [ember-wormhole](https://github.com/yapplabs/ember-wormhole)).
Additionally, I have corrected some misleading documentation reported in #81
> Modal container component, modal documentation improvements

- tests/dummy/app/templates/buttons.hbs
Imo it's not necessary to build a new component for this, but it's nice to have an example in our docs
````handlebars
<div class="fixed-action-btn">
{{md-btn icon='mdi-content-add' action='debug' buttonType='floating' class='btn-large lime darken-2'}}
<ul>
<li>{{md-btn icon='mdi-action-class' action='debug' buttonType='floating' class='indigo'}}</li>
<li>
{{md-btn icon='mdi-action-grade' action='debug' buttonType='floating' class='deep-purple'}}
</li>
<li>
{{md-btn icon='mdi-action-redeem' action='debug' buttonType='floating' class='green'}}
</li>
<li>
{{md-btn icon='mdi-alert-warning' action='debug' buttonType='floating' class='amber darken-3'}}
</li>
</ul>
</div>
````
> Fixed floating button group example in docs

- addon/components/-md-fixed-btn-base.js
- addon/components/md-fixed-btn.js
- addon/components/md-fixed-btns.js
- addon/templates/components/md-fixed-btn.hbs
- addon/templates/components/md-fixed-btns.hbs
- app/components/md-fixed-btn.js
- app/components/md-fixed-btns.js
- tests/dummy/app/controllers/buttons.js
- tests/dummy/app/styles/app.scss
- tests/dummy/app/templates/buttons.hbs
- tests/dummy/config/environment.js
- tests/integration/buttons-test.js
- tests/unit/components/md-fixed-btn-test.js
- tests/unit/components/md-fixed-btns-test.js
After playing with this for a while, it feels like the semantics around fixed floating button groups get needlessly verbose, and are a good candidate for becoming an ember component
````hbs
{{#md-fixed-btns
class="fixed-btns-example"
btnIcon="mdi-content-add"
btnClass="lime darken-2"
action="firstAction"}}
{{md-fixed-btn
btnClass="indigo"
btnIcon="mdi-action-class"
action="anotherAction"}}
{{md-fixed-btn
btnClass="deep-purple"
btnIcon="mdi-content-grade"
action="otherAction"}}
{{md-fixed-btn
btnClass="green"
btnIcon="mdi-action-redeem"
action="someAction"}}
{{md-fixed-btn
btnClass="green"
btnIcon="mdi-alert-warning"
action="myAction"}}
{{/md-fixed-btns}}
````
> [Enhancement] Floating button group

- addon/components/md-collapsible.js
- addon/templates/components/md-collapsible.hbs
- tests/dummy/app/controllers/collapsible.js
- tests/dummy/app/templates/collapsible.hbs
- tests/integration/collapsible-test.js
As per this issue:
https://github.com/sgasser/ember-cli-materialize/issues/112
now, md-collapsible can be made to split out an action when a user interacts with it:
```handlebars
{{#md-card-collapsible id="action-selection"}}
{{#md-collapsible icon="mdi-image-filter-drama" title="Cloud" action="clicked" model="cloud"}}
O misty eye of the mountain below
{{/md-collapsible}}
{{#md-collapsible icon="mdi-maps-place" title="Marker" action="clicked" model="marker"}}
keep careful watch of my brothers' souls
{{/md-collapsible}}
{{#md-collapsible icon="mdi-social-whatshot" title="Fire" action="clicked" model="fire"}}
and should the sky be filled with fire and smoke, keep watching over [indecipherable]
{{/md-collapsible}}
{{/md-card-collapsible}}
```
If provided with action, it is now possible to …
> make md-collapsible actionable

- .travis.yml
- package.json
- tests/dummy/app/styles/app.scss
- tests/dummy/app/templates/application.hbs
I got some complaints that it was hard to find the items in the horizontally-scrolling navbar. 
CC: @ladyleet
> Sidenav instead of navbar for demo app

- addon/templates/components/md-input-date.hbs
sidenote: what's the plan for moving to new bound attribute syntax?
> fix typo in md-input-date

- README.md
- addon/components/md-navbar.js
- addon/components/md-tab.js
- addon/components/md-tabs.js
- addon/templates/components/md-navbar.hbs
- bower.json
- tests/dummy/app/styles/app.scss
- tests/dummy/app/templates/application.hbs
- tests/dummy/app/templates/index.hbs
- tests/dummy/app/views/application.js
this.nearestWithProperty still is not working in a certain scenario with tabs, but I have found a workaround by using the view registry. In a future version, I'll remove this hack, but better to get all tests passing in the current release sooner and find a proper fix (or apply a framework fix) later.
> Ember 1.13 workarounds

- README.md
- addon/components/md-btn.js
- addon/components/md-loader.js
- addon/components/md-modal-container.js
- addon/components/md-modal.js
- addon/mixins/uses-settings.js
- addon/services/md-settings.js
- addon/templates/components/md-modal.hbs
- app/initializers/md-settings.js
- app/services/md-settings.js
- blueprints/ember-cli-materialize/index.js
- bower.json
- config/environment.js
- package.json
- tests/unit/components/materialize-button-test.js
- tests/unit/components/md-modal-container-test.js
- tests/unit/initializers/md-settings-test.js
- tests/unit/services/md-settings-test.js
Moving forward, any default values that might be useful to set on a per-app basis should be moved to a `md-settings` service. Consuming apps can then use their **config/environment.js** file to tweak as desired.
```js
module.exports = function(/* environment, appConfig */) {
var ENV = {
materializeDefaults: {
modalIsFooterFixed: false,
buttonIconPosition: 'left',
loaderSize:         'big',
loaderMode:         'indeterminate',
modalContainerId:   'materialize-modal-root-element'
},
...
};
}
```
> Configurable default values

- blueprints/ember-cli-materialize/files/app/styles/app.scss
needed with materialize.css 0.97.  Fixes issue #171
> Removed blueprint temporary fix for materialize.css that is no longer

- addon/components/md-select.js
Observer was causing timing issues - check for presence of element before using it.
> Observer timing issues

- addon/services/md-settings.js
Keeping IE8 compatibility, as per https://github.com/emberjs/data/issues/3465
> Remove Ember.keys deprecation warning

- addon/components/md-btn-dropdown.js
It fixes null `_dropdownContentId` which causes all dropdowns on the page
having the same menu items.
I'm not sure what the root cause of the problem, but it looks like
component's `element` is null when it's initializing. Using `elementId`
fixes it.
I'm seing this problem on a blank new Ember 1.13.1 project.
With the following code both dropdowns have 'one', 'two' and 'three' menu items before this fix is applied, it works correctly when I changed `element.id` to `elementId`:
```handlebars
{{#md-btn-dropdown text='Button' belowOrigin="true" }}
<li><a href="#!">one</a></li>
<li><a href="#!">two</a></li>
<li><a href="#!">three</a></li>
{{/md-btn-dropdown}}
{{#md-btn-dropdown text='Second button' belowOrigin="true" }}
<li><a href="#!">four</a></li>
<li><a href="#!">five</a></li>
<li><a …
```
> Using elementId in dropdown instead of element.id

- addon/components/md-btn-dropdown.js
- tests/dummy/app/templates/snippets/buttons-dropdown.hbs
- tests/unit/components/materialize-button-dropdown-test.js
The md-btn-dropdown component requires `'true'`/`'false'` attribute strings where it could be simply using booleans, due to the `=== 'true'` comparisons. This is also causing the `constrainWidth` default of `true` passed to `this.getWithDefault` to fail, as `true` is not `===` to `'true'`.
> Switched md-btn-dropdown boolean attributes to use booleans

- addon/components/md-btn.js
- tests/dummy/app/templates/snippets/buttons-flat.hbs
- tests/unit/components/materialize-radios-test.js
Fixes #157 
@samselikoff I took another look, and this can easily be done while maintaining backwards compatibility.
```hbs
{{#md-btn action='debug'
buttonType='flat'
class='purple lighten-2 white-text'}}
Buttons
{{/md-btn}}
{{#md-btn action='debug'
buttonType='flat'
class='yellow black-text'
wavesClass='waves-dark'}}
Are
{{/md-btn}}
```
> Allow customization of button waves

- addon/components/md-input-field.js
- addon/templates/components/md-input.hbs
- tests/dummy/app/controllers/forms.js
- tests/dummy/app/routes/forms.js
- tests/dummy/app/templates/snippets/form-validation-basic.hbs
- tests/dummy/app/templates/snippets/input-basic.hbs
- tests/dummy/app/templates/snippets/input-types.hbs
- tests/dummy/app/templates/snippets/input-with-icon.hbs
Addresses issue #204 and relies on the workaround mentioned in #186 to add continued support of ember-validations style errors.
> #204 -fix classNameBindings for valid/invalid

- blueprints/ember-cli-materialize/index.js
Updating the dependency here to match package.json.
#191 updated the `ember-key-responder` version in package.json, but this version from the blueprint is used when I installed this as a addon in my project.
> Use key-responder 0.4 in the blueprint as well

- addon/templates/components/md-card-content.hbs
- addon/templates/components/md-card-reveal.hbs
- addon/templates/components/md-pagination.hbs
- tests/integration/cards-test.js
Icons are not displaying from within card and pagination components since materialize was updated to use 'Material Icons' font.
> update components to use material design icon font

- blueprints/ember-cli-materialize/index.js
- package.json
Packages without a blueprint do not need to be inserted into the end-user's project.
- ember-composable-helpers (also upgraded to 1.0.0)
- ember-modal-dialog (also upgraded to 0.8.8)
- ember-truth-helpers
Closes #404
> [v1] Move some dependencies to package.json

- addon/components/md-card-content.js
- addon/components/md-card-reveal.js
- addon/templates/components/md-card-reveal.hbs
Check discussion in https://github.com/emberjs/ember.js/issues/14266
> Update code to comply with Ember 2.8.0.

- addon/components/md-navbar.js
Only access `this.element` when running in the browser.
> FastBoot compatibility for md-navbar component

- addon/components/md-select.js
- addon/templates/components/md-select.hbs
Similar to this PR in v1 branch https://github.com/mike-north/ember-cli-materialize/pull/627
> Trigger actions from md-select.

- addon/components/selectable-item.js
- blueprints/ember-cli-materialize/index.js
- package.json
- tests/dummy/app/components/example-snippet.js
- tests/dummy/app/components/options-panel.js
- yarn.lock
ember-new-computed dependency no longer required as described in issue  #715
> feat: remove ember-new-computed dependency
